services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ethereum_explorer
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
